#
# This file is automatically generated by the Terraform inventory module
#
---
all:
  vars:
    vcenter:
      host: ${ vsphere_server }
      username: ${ user }
      password: ${ password }
      allow_unverified_ssl: ${ allow_unverified_ssl }
  hosts:
%{ for item in gfs ~}%{ for types in item.cluster ~}%{ for vm in types ~}
    ${ vm.clone[0].customize[0].network_interface[0].ipv4_address }:
      hostname: ${ vm.name }
      uuid: ${ vm.id }
      fqdn: ${ vm.clone[0].customize[0].linux_options[0].host_name }.${ vm.clone[0].customize[0].linux_options[0].domain }
%{ endfor ~}%{ endfor ~}%{ endfor ~}

  children:
    gfs_vm:
      children:
%{ for item in gfs ~}
        gfs_vm_primary_${ item.cluster_id }:
          hosts:
%{ for vm in item.cluster.gfs_primary ~}
            ${ vm.clone[0].customize[0].network_interface[0].ipv4_address }:
              hostname: ${ vm.name }
              uuid: ${ vm.id }
              fqdn: ${ vm.clone[0].customize[0].linux_options[0].host_name }.${ vm.clone[0].customize[0].linux_options[0].domain }
              data_disks:
%{ for i in range(1, length(vm.disk)) ~}
                - sd${ ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n"][i] }
%{ endfor ~}
%{ endfor ~}
%{ endfor ~}
%{ for item in gfs ~}
        gfs_vm_secondary_${ item.cluster_id }:
          hosts:
%{ for vm in item.cluster.gfs_secondary ~}
            ${ vm.clone[0].customize[0].network_interface[0].ipv4_address }:
              hostname: ${ vm.name }
              uuid: ${ vm.id }
              fqdn: ${ vm.clone[0].customize[0].linux_options[0].host_name }.${ vm.clone[0].customize[0].linux_options[0].domain }
              data_disks:
%{ for i in range(1, length(vm.disk)) ~}
                - sd${ ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n"][i] }
%{ endfor ~}
%{ endfor ~}
%{ endfor ~}

#
# EOF
#

