---
- name: Extend root lvm partition
  include: extend_lvm.yml

- name: Disable firewall
  include: firewall.yml

- name: Disable SELinux
  include: selinux.yml

- name: Create user account
  include: user.yml

- name: Update hosts file
  include: hosts_file.yml
