---
- name: Create user account
  user:
    name: "{{ vars.vm_user }}"
    password: "{{ vars.vm_pass | password_hash('sha512', 'VMware1') }}"
    groups: wheel
    append: yes

- name: Set authorized key taken from file
  ansible.posix.authorized_key:
    user: "{{ vars.vm_user }}"
    state: present
    key: "{{ lookup('file', vars.vm_ssh_key_file) }}"
