#
# This file is automatically generated by the Terraform inventory module
#
---
all:
  vars:

    # Ansible
    ansible_connection: ssh
    ansible_user: ${ vm_user }
    ansible_ssh_private_key_file: ${ vm_ssh_private_key_file }

    # vCenter
    vcenter:
      host: ${ vcenter_server }
      username: ${ vcenter_user }
      password: ${ vcenter_password }
      allow_unverified_ssl: ${ vcenter_allow_unverified_ssl }

    # vSphere
    vsphere:
      datacenter: ${ vsphere_datacenter }
      cluster: ${ vsphere_cluster }

    # VM
    data_disk_count: ${ vm_disk_data_count }

  hosts:

  children:
    gfs_primary:
      hosts:
%{ for vm in vms_primary ~}
        ${ vm.clone[0].customize[0].network_interface[0].ipv4_address }:
          hostname: ${ vm.name }
          fqdn: ${ vm.clone[0].customize[0].linux_options[0].host_name }.${ vm.clone[0].customize[0].linux_options[0].domain }
          uuid: ${ vm.id }
          public_ip: ${ vm.clone[0].customize[0].network_interface[0].ipv4_address }
          private_ip: ${ vm.clone[0].customize[0].network_interface[1].ipv4_address }
%{ endfor ~}

    gfs_secondary:
      hosts:
%{ for vm in vms_secondary ~}
        ${ vm.clone[0].customize[0].network_interface[0].ipv4_address }:
          hostname: ${ vm.name }
          fqdn: ${ vm.clone[0].customize[0].linux_options[0].host_name }.${ vm.clone[0].customize[0].linux_options[0].domain }
          uuid: ${ vm.id }
          public_ip: ${ vm.clone[0].customize[0].network_interface[0].ipv4_address }
          private_ip: ${ vm.clone[0].customize[0].network_interface[1].ipv4_address }

%{ endfor ~}

#
# EOF
#

