---
#- name: initilize data disks
#  vars:
#    data_filesystem: xfs
#    data_mount_opts: noatime
#    data_mount_folder: /pcs_deploy
#    data_mount_prefix: data
#  include: initialize_data_disks.yml

- name: configure sysctl vm.dirty_background_ratio
  ansible.posix.sysctl:
     name: vm.dirty_background_ratio
     value: '20'
     state: present

- name: configure sysctl vm.vfs_cache_pressure
  ansible.posix.sysctl:
     name: vm.vfs_cache_pressure
     value: '500'
     state: present

- name: install required packages
  dnf:
    name:
      - dlm-lib
      - pcs
      - fence-agents-all
      - gfs2-utils
      - pcp-zeroconf
    enablerepo: ha
    state: present

- name: install patched dlm
  yum:
    name: "{{ dlm_rpm }}"
    validate_certs: no
    disable_gpg_check: yes
    state: present

- name: set hacluster user password
  user:
    name: hacluster
    password: "{{ 'vmware' | password_hash('sha512') }}"

- name: start pcsd service
  ansible.builtin.service:
    name: pcsd
    state: started
    enabled: yes

- name: configure pcs
  include: configure_pcs.yml
  when: inventory_hostname == play_hosts[0]

- name: create vg and filesystem
  include: configure_vg.yml

- name: configure gfs2
  include: configure_gfs.yml
  when: inventory_hostname == play_hosts[0]