---
- name: Install LVM2
  ansible.builtin.yum:
    name: lvm2
    state: latest

- name: Configure sysctl vm.dirty_background_ratio
  ansible.posix.sysctl:
     name: vm.dirty_background_ratio
     value: '20'
     state: present

- name: Configure sysctl vm.vfs_cache_pressure
  ansible.posix.sysctl:
     name: vm.vfs_cache_pressure
     value: '500'
     state: present

# https://access.redhat.com/solutions/6958415
- name: Enable lvmlockd (https://access.redhat.com/solutions/6958415)
  lineinfile:
    dest: /etc/lvm/lvm.conf
    regexp: '#\s*use_lvmlockd\s*=\s*\d+\s*$'
    line: '        use_lvmlockd = 1'

- name: Install required packages
  ansible.builtin.yum:
    name:
      - dlm
      - dlm-lib
      - pcs
      - fence-agents-all
      - gfs2-utils
      - pcp-zeroconf
    enablerepo: ha
    state: present

- name: Install required packages for RHEL9
  ansible.builtin.yum:
    name:
      - lvm2-lockd
    enablerepo: ha
    state: present
  when: ansible_distribution_major_version | int == 9

#- name: Install patched dlm when RHEL 8
#  ansible.builtin.yum:
#    name: "{{ dlm_rpm }}"
#    validate_certs: no
#    disable_gpg_check: yes
#    state: present
#  when: ansible_distribution_major_version | int == 8
#
#- name: Install DLM when RHEL 9
#  ansible.builtin.yum:
#    name:
#      - dlm
#    enablerepo: ha
#    state: present
#  when: ansible_distribution_major_version | int == 9

- name: set hacluster user password
  ansible.builtin.user:
    name: hacluster
    group: haclient
    password: "{{ hacluster_password | password_hash('bcrypt') }}"

- name: start pcsd service
  ansible.builtin.service:
    name: pcsd
    state: started
    enabled: yes

- name: Stop default cluster
  ansible.builtin.command: "pcs cluster stop --force"
  register: result

- name: Destroy default cluster
  ansible.builtin.command: "pcs cluster destroy"
  register: result

- name: configure pcs
  include: configure_pcs.yml
  when: inventory_hostname == play_hosts[0]

- name: create vg and filesystem
  include: configure_vg.yml

- name: configure gfs2
  include: configure_gfs.yml
  when: inventory_hostname == play_hosts[0]