---
- name: Wait for systems to boot up
  hosts: all
  gather_facts: no
  any_errors_fatal: true
  tasks:
    - name: Wait up to 300 seconds
      wait_for_connection:
        delay: 3
        sleep: 5
        timeout: 300


- name: Get IP
  hosts: localhost
  gather_facts: no
  any_errors_fatal: true
  tasks:
    - name: Fetch selected facts
      ansible.builtin.setup:
        filter:
          - 'ansible_distribution'
          - 'ansible_default_ipv4'
    - set_fact:
        appliance_ip: "{{ ansible_default_ipv4.address }}"

- name: Apply basic system configurations
  hosts: all
  any_errors_fatal: true
  become: yes
  roles:
    - selinux
    - firewall
    - hosts

- name: Red Hat
  hosts: all
  any_errors_fatal: true
  gather_facts: no
  become: yes
  tasks:
    - name: Fetch selected facts
      ansible.builtin.setup:
        filter:
          - 'ansible_distribution'

    - name: Register with activationkey and consume subscriptions
      redhat_subscription:
        state: present
        force_register: yes
        activationkey: automation-gfs
        org_id: 16794691
        pool_ids:
          - 2c94cfaa86a4481c0186a8746290199f
      when: ansible_distribution == 'RedHat'

    - name: Enable RedHat HA repository
      community.general.rhsm_repository:
        name: rhel-8-for-x86_64-highavailability-rpms
      when: ansible_distribution == 'RedHat'

- name: Deploy PCS
  hosts: all
  become: yes
  vars:
    dlm_rpm: "http://{{ hostvars['localhost']['appliance_ip'] }}/dlm/dlm-4.1.0-1.el8.x86_64.rpm"
    hacluster_password: vmware
  roles:
    - role: pcs_deploy
      any_errors_fatal: true

